<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find rollerwalker_sim)/xacro/include/rollerwalker_macro.xacro" />
     <!-- 脚のマクロ -->
    <xacro:macro name="leg_macro" params="leg_posi">
        <!-- ジョイント1-->
        <joint name="joint_1_${leg_posi}" type="revolute">
            <parent link="body"/>
            <child  link="joint_1_link_${leg_posi}"/>
            <axis xyz="0 0 1"/>
            <!-- lf -->
            <xacro:if value="${leg_posi=='lf'}">
                <origin xyz="${body_length/2 - joint_1_radius/2} ${body_width/2 - joint_1_radius/2} 0.0" rpy="0 3.141519 -1.5708"/>
            </xacro:if>
            <!-- lr -->
            <xacro:if value="${leg_posi=='lr'}">
                <origin xyz="${-(body_length/2 - joint_1_radius/2)} ${body_width/2 - joint_1_radius/2} 0.0" rpy="0 3.141519 -1.5708"/>
            </xacro:if>
            <!-- rr -->
            <xacro:if value="${leg_posi=='rr'}">
                <origin xyz="${-(body_length/2 - joint_1_radius/2)} ${-(body_width/2 - joint_1_radius/2)} 0.0" rpy="0 0 -1.5708"/>
            </xacro:if>
            <!-- rf -->
            <xacro:if value="${leg_posi=='rf'}">
                <origin xyz="${body_length/2 - joint_1_radius/2} ${-(body_width/2 - joint_1_radius/2)} 0.0" rpy="0 0 -1.5708"/>
            </xacro:if>
            <limit lower="-0.4" upper="0.4" effort="${effort_limit}" velocity="100"/>    
            <dynamics damping="${joint_1_damping}"/>
        </joint>

        <link name = "joint_1_link_${leg_posi}">
            <inertial>
                <mass value="${joint_1_mass}"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="${I_joint_1_xx}" ixy="0.0" ixz="0.0" iyy="${I_joint_1_yy}" iyz="0.0" izz="${I_joint_1_zz}"/>
            </inertial>
            <visual>
                <geometry>
                    <cylinder radius="${joint_1_radius}" length="${joint_1_thickness}"/> 
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/> 
                <material name = "blue"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${joint_1_radius}" length="${joint_1_thickness}"/> 
                </geometry>
            </collision>
        </link>
        <gazebo reference="joint_1_link_${leg_posi}">
            <material>Gazebo/Blue</material>
            <!-- <kp value="${kp}" /> -->
            <!-- <kd value="10" /> -->
        </gazebo>

        <!-- ジョイント２の設定 -->
        <joint name="joint_2_${leg_posi}" type="revolute">
            <axis xyz="0 -1 0"/>
            <parent link="joint_1_link_${leg_posi}"/>
            <child  link="link_2_${leg_posi}"/>
            <xacro:if value="${leg_posi=='lf'}">
                <origin rpy="3.141519 0 0" xyz="0 0 0"/>
            </xacro:if>
            <xacro:if value="${leg_posi=='lr'}">
                <origin rpy="3.141519 0 0" xyz="0 0 0"/>
            </xacro:if>
            <xacro:if value="${leg_posi=='rr'}">
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </xacro:if>
            <xacro:if value="${leg_posi=='rf'}">
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </xacro:if>
            <dynamics damping="${joint_1_to_joint_2_damping}"/>
            <limit lower="-1.5" upper="1.5" effort="${effort_limit}" velocity="100"/>
        </joint>

        <!-- リンク2の描画 -->
        <link name = "link_2_${leg_posi}">
            <inertial>
                <mass value="${link_2_mass}"/>
                <origin xyz="${link_2_x/2} 0 0.0" rpy="0 0 0"/> 
                <inertia ixx="${I_link_2_xx}" ixy="0.0" ixz="0.0" iyy="${I_link_2_yy}" iyz="0.0" izz="${I_link_2_zz}"/>
            </inertial>
            <visual>
                <geometry>
                    <box size = "${link_2_x} ${link_2_y} ${link_2_z}" />
                </geometry>
                <origin xyz="${link_2_x/2} 0 0.0" rpy="0 0 0"/> 
                <material name = "white"/>
            </visual>
            <collision>
                <origin xyz="${link_2_x/2} 0 0.0" rpy="0 0 0"/> 
                <geometry>
                    <box size = "${link_2_x} ${link_2_y} ${link_2_z}" /> 
                </geometry>
            </collision>
        </link>
        <gazebo reference="link_2_${leg_posi}">
            <material>Gazebo/White</material>
        </gazebo>

        <!-- ジョイント3の設定 -->
        <joint name="joint_3_${leg_posi}" type="revolute">
            <axis xyz="0 -1 0"/>
            <parent link="link_2_${leg_posi}"/>
            <child  link="link_3_${leg_posi}"/>
            <origin rpy="0 1.5708 0" xyz="${link_2_x} 0 0"/>
            <dynamics damping="${link_2_to_joint_3_damping}"/>
            <limit lower="-2.0" upper="1.5" effort="${effort_limit}" velocity="100"/>
        </joint>
        
        <link name = "link_3_${leg_posi}">
            <inertial>
                <mass value="${link_3_mass}"/>
                <origin xyz="${link_3_x/2} 0 0.0" rpy="0 0 0"/> 
                <inertia ixx="${I_link_3_xx}" ixy="0.0" ixz="0.0" iyy="${I_link_3_yy}" iyz="0.0" izz="${I_link_3_zz}"/>
            </inertial>
            <visual>
                <geometry>
                    <box size = "${link_3_x} ${link_3_y} ${link_3_z}" />
                </geometry>
                <origin xyz="${link_3_x/2} 0 0.0" rpy="0 0 0"/> 
                <material name = "white"/>
            </visual>
            <collision>
                <origin xyz="${link_3_x/2} 0 0.0" rpy="0 0 0"/> 
                <geometry>
                    <box size = "${link_3_x} ${link_3_y} ${link_3_z}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="link_3_${leg_posi}">
            <material>Gazebo/White</material>
            <!-- <kp value="${kp}" /> -->
            <!-- <kd value="10" /> -->
        </gazebo>

        <!-- ジョイント4の設定 -->
        <joint name="joint_4_${leg_posi}" type="revolute">
            <axis xyz="0 -1 0"/>
            <parent link="link_3_${leg_posi}"/>
            <child  link="link_4_${leg_posi}"/>
            <origin rpy="0 -1.57070 0" xyz="${link_3_x} 0 0"/>
            <dynamics damping="${link_3_to_joint_4_damping}"/>
            <limit lower="-2.0" upper="1.5" effort="${effort_limit}" velocity="100"/>
        </joint>
        
        <link name = "link_4_${leg_posi}">
            <inertial>
                <mass value="${link_4_mass}"/>
                <origin xyz="${link_4_x/2} 0 0.0" rpy="0 0 0"/>
                <inertia ixx="${I_link_4_xx}" ixy="0.0" ixz="0.0" iyy="${I_link_4_yy}" iyz="0.0" izz="${I_link_4_zz}"/>
            </inertial>
            <visual>
                <geometry>
                    <box size = "${link_4_x} ${link_4_y} ${link_4_z}" />
                </geometry>
                <origin xyz="${link_4_x/2} 0 0.0" rpy="0 0 0"/> 
                <material name = "red"/>
            </visual>
            <collision>
                <origin xyz="${link_4_x/2} 0 0.0" rpy="0 0 0"/> 
                <geometry>
                    <box size = "${link_4_x} ${link_4_y} ${link_4_z}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="link_4_${leg_posi}">
            <material>Gazebo/Red</material>
            <!-- <kp value="${kp}" /> -->
            <!-- <kd value="10" /> -->
        </gazebo>


        <!-- リンク4とホイールの設定 -->
        <joint name="link_4_${leg_posi}_to_wheel_${leg_posi}" type="continuous">
            <axis xyz="0 0 1"/>
            <parent link="link_4_${leg_posi}"/>
            <child  link="wheel_${leg_posi}"/>
            <origin rpy="0 1.57070 0" xyz="${link_4_x + wheel_thickness/2} 0 0"/>
            <dynamics damping="${link_4_to_wheel_damping}" />
            <!-- <limit lower="-1.79769e+308" upper="1.79769e+308" effort="0" velocity="0"/> -->
        </joint>

        <!-- ホイールの描画 -->
        <link name = "wheel_${leg_posi}">
            <inertial>
                <mass value="${wheel_mass}"/>
                <origin xyz="0 0 0.0" rpy="0 0 0"/> 
                <inertia ixx="${I_wheel_xx}" ixy="0.0" ixz="0.0" iyy="${I_wheel_yy}" iyz="0.0" izz="${I_wheel_zz}"/>
            </inertial>
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/> 
                </geometry>
                <origin xyz="0 0 0.0" rpy="0 0 0"/> 
                <material name = "blue"/>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0"/> 
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/> 
                </geometry>
            </collision>
        </link>
        <gazebo reference="wheel_${leg_posi}">
            <material>Gazebo/Blue</material>
            <mu1>${mu}</mu1>
            <mu2>${mu_2}</mu2>
            <fdir1>1 0 0</fdir1>
            <!-- <kp value="0.0001" />
            <kd value="0.2" /> -->
        </gazebo>

        <!-- トランスミッション -->
        <transmission name="joint_1_${leg_posi}_trans" >
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$joint_1_${leg_posi}_motor">
              <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="joint_1_${leg_posi}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>
        <!-- ジョイント2のトランスミッション -->
        <transmission name="joint_2_${leg_posi}_trans" >
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$joint_2_${leg_posi}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="joint_2_${leg_posi}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <!-- ジョイント3のトランスミッション -->
        <transmission name="joint_3_${leg_posi}_trans" >
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$joint_3_${leg_posi}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="joint_3_${leg_posi}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
         </transmission>

        <!-- ジョイント4のトランスミッション -->
        <transmission name="joint_4_${leg_posi}_trans" >
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$joint_4_${leg_posi}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="joint_4_${leg_posi}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
         </transmission>

        <!-- ホイールのトランスミッション  -->
        <transmission name="wheel_trans" >
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="$wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="link_4_${leg_posi}_to_wheel_${leg_posi}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>  
</robot>