rollerwalker_param:
 #ローラーウォーカーの4つのパラメータ
 d_0: 0.08              #接線方向の振幅
 theta_0_lf: 0.30       #法線方向の振幅
 theta_0_lr: 0.30       #法線方向の振幅
 theta_0_rr: 0.30       #法線方向の振幅
 theta_0_rf: 0.30       #法線方向の振幅
 omega: 3.1415926536    #周期関数の角速度(PI)
 phi: 1.5707963268      #接線方向と法線方向の周期関数の位相差
 phi_fr: 1.5707963268   #前脚と後ろ足の周期関数の位相差
#  phi_fr: 0   #前脚と後ろ足の周期関数の位相差

 #ステアリングオフセット
 steering_ofset_lf: 0
 steering_ofset_lr: 0
 steering_ofset_rr: 0
 steering_ofset_rf: 0
 #本体の高さ
 center_z: 0.15
 # タイヤの半径
 wheel_radius: 0.035
 wheel_thicness: 0.024
 # ボディーの横幅
 body_width: 0.29
 #リンクの長さ
 l2: 0.2
 l3: 0.188
 l4: 0.031

# 計算周期
publish_frequency: 100
file_write_frequency: 10