# 計算周期
publish_frequency: 200
file_write_frequency: 100

#ファイル名
position_file_name: "/home/lab/Desktop/卒検/sim_data/pivot_turn/omega/omega=2PI/true_position.csv"
velocity_file_name: "/home/lab/Desktop/卒検/sim_data/pivot_turn/omega/omega=2PI/true_velocity.csv"

#ローラーウォーカー関連
rollerwalker_param:
 #ローラーウォーカーの4つのパラメータ
 d_0: 0.08              #接線方向の振幅
 theta_0_lf: -0.30       #法線方向の振幅
 theta_0_lr: -0.30       #法線方向の振幅
 theta_0_rr: 0.30       #法線方向の振幅
 theta_0_rf: 0.30       #法線方向の振幅

#  omega: 0.78539816339    #周期関数の角速度(PI/4)
#  omega: 1.57079632679    #周期関数の角速度(PI/2)
#  omega: 2.35619449019    #周期関数の角速度(3PI/4)
 omega: 3.14159265359    #周期関数の角速度(PI)
#  omega: 3.92699081699    #周期関数の角速度(5PI/4)
#  omega: 4.71238898038    #周期関数の角速度(3PI/2)
#  omega: 5.49778714378    #周期関数の角速度(7PI4)
#  omega: 6.28318530718    #周期関数の角速度(2PI)

 phi: 1.5707963268      #接線方向と法線方向の周期関数の位相差

 phi_fr: 0.0                #前脚と後ろ足の周期関数の位相差
#  phi_fr: 0.78539816339    #前脚と後ろ足の周期関数の位相差(PI/4)
#  phi_fr: 1.57079632679    #前脚と後ろ足の周期関数の位相差(PI/2)
#  phi_fr: 2.35619449019    #前脚と後ろ足の周期関数の位相差(3PI/4)
#  phi_fr: 3.14159265359    #前脚と後ろ足の周期関数の位相差(PI)
#  phi_fr: 3.92699081699    #前脚と後ろ足の周期関数の位相差(5PI/4)
#  phi_fr: 4.71238898038    #前脚と後ろ足の周期関数の位相差(3PI/2)
#  phi_fr: 5.49778714378    #前脚と後ろ足の周期関数の位相差(7PI4)

 

 #ステアリングオフセット
 steering_ofset_lf: 0.20
 steering_ofset_lr: -0.20
 steering_ofset_rr: -0.20
 steering_ofset_rf: 0.20

 #本体の高さ
 center_z: 0.15
 # タイヤの半径
 wheel_radius: 0.035
 wheel_thicness: 0.024
 # ボディーの横幅
 body_width: 0.29
 #リンクの長さ
 l2: 0.2
 l3: 0.188
 l4: 0.031

