rollerwalker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  # lf
  joint_1_lf_trans:
    type: effort_controllers/JointPositionController
    joint: body_to_joint_1_lf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_2_lf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_lf_to_joint_2_lf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_3_lf_trans:
    type: effort_controllers/JointPositionController
    joint: link_2_lf_to_joint_3_lf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_4_lf_trans:
    type: effort_controllers/JointPositionController
    joint: link_3_lf_to_joint_4_lf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  
    

  # lr
  joint_1_lr_trans:
    type: effort_controllers/JointPositionController
    joint: body_to_joint_1_lr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  
    

  joint_2_lr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_lr_to_joint_2_lr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_3_lr_trans:
    type: effort_controllers/JointPositionController
    joint: link_2_lr_to_joint_3_lr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_4_lr_trans:
    type: effort_controllers/JointPositionController
    joint: link_3_lr_to_joint_4_lr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  # rr
  joint_1_rr_trans:
    type: effort_controllers/JointPositionController
    joint: body_to_joint_1_rr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_2_rr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_rr_to_joint_2_rr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_3_rr_trans:
    type: effort_controllers/JointPositionController
    joint: link_2_rr_to_joint_3_rr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_4_rr_trans:
    type: effort_controllers/JointPositionController
    joint: link_3_rr_to_joint_4_rr
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  # rf
  joint_1_rf_trans:
    type: effort_controllers/JointPositionController
    joint: body_to_joint_1_rf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10  

  joint_2_rf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_rf_to_joint_2_rf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10 

  joint_3_rf_trans:
    type: effort_controllers/JointPositionController
    joint: link_2_rf_to_joint_3_rf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10 

  joint_4_rf_trans:
    type: effort_controllers/JointPositionController
    joint: link_3_rf_to_joint_4_rf
    pid: {p: 1000.0, i: 10.0, d: 1.0}
    publish_rate: 10 

  #wheel
  wheel_lf_trans:
    type: velocity_controllers/JointPositionController
    joint: link_4_lf_to_wheel_lf
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 10 
  
  wheel_lr_trans:
    type: velocity_controllers/JointPositionController
    joint: link_4_lr_to_wheel_lr
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 10 
  
  wheel_rr_trans:
    type: velocity_controllers/JointPositionController
    joint: link_4_rr_to_wheel_rr
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 10 
  
  wheel_rf_trans:
    type: velocity_controllers/JointPositionController
    joint: link_4_rf_to_wheel_rf
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 10 