rollerwalker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  # lf
  joint_1_lf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_lf
    pid: {p: 100.0, i: 8.0.0, d: 20} #joint_1
    publish_rate: 100  

  joint_2_lf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_2_lf
    pid: {p: 550.0, i: 8, d: 20.0} #joint_2
    publish_rate: 100  

  joint_3_lf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_3_lf
    pid: {p: 300.0, i: 20.0, d: 30.0} #joint_3
    publish_rate: 100  

  joint_4_lf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_4_lf
    pid: {p: 300.0, i: 8.0, d: 0} #joint_4
    publish_rate: 100  
    

  # lr
  joint_1_lr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_lr
    pid: {p: 100.0, i: 8.0.0, d: 20} #joint_1
    publish_rate: 100  
    

  joint_2_lr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_2_lr
    pid: {p: 550.0, i: 8, d: 20.0} #joint_2
    publish_rate: 100  

  joint_3_lr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_3_lr
    pid: {p: 300.0, i: 20.0, d: 30.0} #joint_3
    publish_rate: 100  

  joint_4_lr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_4_lr
    pid: {p: 300.0, i: 8.0, d: 0} #joint_4
    publish_rate: 100  

  # rr
  joint_1_rr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_rr
    pid: {p: 100.0, i: 8.0.0, d: 20} #joint_1
    publish_rate: 100  

  joint_2_rr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_2_rr
    pid: {p: 550.0, i: 8, d: 20.0} #joint_2
    publish_rate: 100  

  joint_3_rr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_3_rr
    pid: {p: 300.0, i: 20.0, d: 30.0} #joint_3
    publish_rate: 100  

  joint_4_rr_trans:
    type: effort_controllers/JointPositionController
    joint: joint_4_rr
    pid: {p: 300.0, i: 8.0, d: 0} #joint_4
    publish_rate: 100  

  # rf
  joint_1_rf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_1_rf
    pid: {p: 100.0, i: 8.0.0, d: 20} #joint_1
    publish_rate: 100  

  joint_2_rf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_2_rf
    pid: {p: 550.0, i: 8, d: 20.0} #joint_2
    publish_rate: 100  

  joint_3_rf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_3_rf
    pid: {p: 300.0, i: 20.0, d: 30.0} #joint_3
    publish_rate: 100  

  joint_4_rf_trans:
    type: effort_controllers/JointPositionController
    joint: joint_4_rf
    pid: {p: 300.0, i: 8.0, d: 0} #joint_4
    publish_rate: 100  

  #wheel
  wheel_lf_trans:
    type: effort_controllers/JointPositionController
    joint: link_4_lf_to_wheel_lf
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 100  
  
  wheel_lr_trans:
    type: effort_controllers/JointPositionController
    joint: link_4_lr_to_wheel_lr
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 100  
  
  wheel_rr_trans:
    type: effort_controllers/JointPositionController
    joint: link_4_rr_to_wheel_rr
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 100  
  
  wheel_rf_trans:
    type: effort_controllers/JointPositionController
    joint: link_4_rf_to_wheel_rf
    pid: {p: 0.0, i: 0.0, d: 0.0}
    publish_rate: 100  